version: "3.9"
services:
  web:
    container_name: web
    build: docker/nginx
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./application:/var/www/html
      - ./docker/nginx/ssl:/etc/ssl/custom
    networks:
      - backend
  php:
    container_name: fpm
    build:
      args:
        user: deployer
        uid: 1000
      context: ./docker/php
    volumes:
      - ./application:/var/www/html
    working_dir: /var/www/html/
    command: php-fpm
    ports:
      - 9000
    env_file: ./application/.env
    networks:
      - backend
  db:
    image: mysql:8
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - sql_volume:/var/lib/mysql
    ports:
      - 3306:3306
    env_file: 
      - .dockerenv
    networks:
      - backend

volumes:
  sql_volume:
networks:
  backend: